### ISSUE TITLE
Salamander Pod's top node issues

### ISSUE THREAD

**Issue by GarwelGarwel** [UmbraSpaceIndustries/MKS#1315]
For some reason, the Salamander Pod has two top attachment nodes (I understand the lower one is 1.25 m and the upper one 2.5 m). However, they are so close that it's impossible to attach many of the parts to the lower one. For example, if you try to attach USI-LS Observation Cupola or Viewing Cupola on top of the pod, a shroud will appear.
![salamander](https://user-images.githubusercontent.com/15203189/29027665-4ed40d4a-7b8a-11e7-8579-9da4967fcea0.jpg)

**Comment by tjdeckard** [comment]
They are close together and it can be tricky to attach things to the proper node but it's not impossible. Just takes some patience and practice. Also, this is why the node helper tool exists. You place it on the node that's causing you grief to make it easier to hit the intended node with the real part. Then you delete the node helper when you're done.

Since this part has already been released into the wild, we can't really make changes to attach nodes without running the risk of breaking a bunch of people's ships. Folks usually don't appreciate having their ships spontaneously combust after a mod gets updated. So your best bet is going to be my advice above.

**Comment by BobPalmer** [comment]
Adding in - there's a handy green node stick included with parts that can help you with tricky nodes.  Just attach it to a node you want occupied, attach your desired part to the remaining node, then remove the stick.
