### ISSUE TITLE
Performance issue with MKS drills 

### ISSUE THREAD

**Issue by sh1pman** [UmbraSpaceIndustries/MKS#1322]
After I added some MKS drills to a stock vessel, the framerate on the launchpad went down from ~80 to 40 fps. Adding fuel tanks instead didn't affect the framerate in any way.

**Comment by fastdelaspeed** [comment]
Hi, I had the same issue. Do you have Ampyear installed? I found that Ampyear would spam the log with an info message about a hundred times a second as soon as a drill was in the scene. I posted on the Ampyear forum as well.

**Comment by sh1pman** [comment]
No, I don't have AmpYear installed. Don't have any log spam either.

**Comment by BobPalmer** [comment]
@sh1pman - Having issues repro'ing this.  Can you confirm you are on the latest MKS/USI Tools version?  Also, which specific drill? (A sample craft may help).

**Comment by sh1pman** [comment]
Sure. I'm using the latest MKS/USI Tools. 
[Kerbal X Drill](https://1drv.ms/u/s!AvN7b2zFExfDin4jaKIVbp4ddWmC)
[Kerbal X No Drill](https://1drv.ms/u/s!AvN7b2zFExfDin2WLU__jjSNtFq8)

**Comment by BobPalmer** [comment]
Ok - I tested this with said craft, still no repro, and a solid 60fps with both vessels.

Not sure why it is being flaky - maybe try to make sure CRP is current?  Longshot but worth trying

**Comment by SteveBenz** [comment]
I have this issue and can confirm @fastdelaspeed 's experience.  I deleted AmpYear, and the problem went away.  I reinstalled it, and it came back.  I suspect that @sh1pman just has another mod that's got the same bad interaction as AmpYear.  I've got AmpYear V1.5.0.0 and USI Core 0.4.2.0 (all the latest CKAN has as of 9/15).  If it'd help, I could fine it down further by seeing if it happens with just AmpYear and USI, but you might try installing AmpYear and see if you can repro the problem and then figure out where the problem lies.

**Comment by BobPalmer** [comment]
Without Ampyear's code about all I will be able to say is 'yup, I see the same thing other folks do'.  Closing this as a mod conflict issue.
