### ISSUE TITLE
MKS/OKS Crew FlexOTubes wont show up in the tech tree, nor the build menu.

### ISSUE THREAD

**Issue by JustaGamer0** [UmbraSpaceIndustries/MKS#1536]
I have been searching for the flex tubes through the Research tree, thinking that I missed something. I had found a post the tubes had been made an optional addition yet don't know what that means or how to fix it. I did search and find that they do indeed exist in the game files but either I'm blind or they are not showing up at all.

**Comment by JustaGamer0** [comment]
It is in the latest version.

**Comment by REVIEWGAMINGMAN** [comment]
yes

**Comment by tjdeckard** [comment]
The Flex-O-Tubes relied on an old version of Kerbal Attachment System that I'm not sure even works anymore in the latest version of KSP. We definitely don't support them anymore. It's common for old parts to be "hidden" so that they can still be loaded by the game for existing vessels but do not show up in the VAB/SPH to be added to new vessels. That's probably what we did with the Flex-O-Tubes. They've been deprecated for a quite a while now, so my memory is fuzzy on their exact fate.
