### ISSUE TITLE
Stock Docking Port docking to MKS Docking Port

### ISSUE THREAD

**Issue by helaeon** [UmbraSpaceIndustries/MKS#245]
Checked to make sure port was not backwards.
Applied both in VAB/SPH and with KAS.
Can dock when active vessel has MKS port and is docking to stock port.
Cannot dock active vessel's standard port to MKS. Ports do not acquire each other in this case, no attractive force.
Two MKS ports does work.

**Comment by Zibit-Meowe** [comment]
Hi, I'm running into the same bug.  So long as other docking ports work, it's minor, but not understanding makes me cranky. :D  
I'm on 2 clean .90 installs, PackRat, M/OKS 22.8 & 22.9 and can reproduce this consistently.  I have logs, screenshots, etc... if you want them.
After editing mks_dockingport.cfg I've gotten a stationary MKS port to attract a controlled size 1 Clamp'oTron.  It seems like the the collider mesh of said MKS port doesn't let the CoT go deep enough to dock.  I don't know enough about KSP or Unity to know how docking is handled, but I've got some free time and I'm willing to help.
Any word on if you've found a fix would be great.  Otherwise, it's off to read some books on modding ksp and the unity engine.
Thanks!

**Comment by jberkman** [comment]
so i've been trying to track this down, and reached an interesting state. i built [two rovers coupled together, one with an MKS port and one with a stock port](https://gist.github.com/jberkman/42a8275aced5deeaf13d). i then try to dock the stock port to the MKS.

i've reached a point where the game thinks the MKS port is docked, but the stock one isn't!

```
PART
{
    name = dockingPort2
    uid = 1316638747
    ...
    MODULE
    {
        name = ModuleDockingNode
        state = Ready
        dockUId = 0
        ...

PART
{
    name = MKS.DockingPort
    uid = 4230658396
    ...
    MODULE
    {
        name = ModuleDockingNode
        state = Docked (dockee)
        dockUId = 1316638747
        ...
```

visually, they are clearly not docked:

![screen shot 2015-08-21 at 07 52 46](https://cloud.githubusercontent.com/assets/1633584/9411369/73dcd0d0-47da-11e5-9868-83f5f7fa80a9.png)

if i back up, the MKS port goes to `state = Ready` but keeps `dockUId = 131...` and is therefore unable to dock again.

i am able to reproduce this with NavyFish Docking Port Alignment Indicator *not* installed.

i can reproduce is when controlling the rover with the MKS port, although sometimes it works. i do wonder if the bug's on the squad part's side?

i've also seen where i try to come in to dock, and the incoming ship stops as if it ran into something, but it was still a few meters away from the port (but this only happened once).

LMK if i can provide any other information.

**Comment by jberkman** [comment]
If I comment out the `acquireRange` & `captureRange` lines in `MKS_DockingPort.cfg` it works a *lot* better.

i'm guessing the MKS port comes into range and thinks it's docked before the stock port?
