### ISSUE TITLE
For Squad's info: MODEL{} nodes and rescaleFactor != 1 don't play nice.

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [UmbraSpaceIndustries/MKS#593]
There are several issues around (#492, and a couple more from KIS: https://github.com/KospY/KIS/issues/53, https://github.com/KospY/KIS/issues/74) that seem to stem from a bug in how KSP reports the sizes of parts that use MODEL{} nodes and non-unity rescaleFactor.  If an affected part (e.g. the 0.31.4 size 2 or 3 Kontainers) is placed into the editor, the dimensions reported in the Engineer's Report are those of the unscaled model; another part has to be attached before the dimensions update to their proper values.  This lack of scaling on initial load probably causes those three issues I linked above.

I raised [this issue](http://bugs.kerbalspaceprogram.com/issues/5290) on Squad's public bug tracker, but they said that's not the place to report it since no stock parts are affected; they'd rather hear about it from an addon-focused channel.  Since your parts are (were, in UKS 0.31.4) affected, I figure you're the best person to tell about this.  Thanks!

**Comment by pellinor0** [comment]
For Completeness: the 'part rescales on reload' bug https://github.com/pellinor0/TweakScale/issues/3 is likely the same as the MKS issue https://github.com/BobPalmer/MKS/issues/492, triggered in another way. 

The requirements for the visual model reverting scale are
* the part is scaled by either rescaleFactor!=1 or TweakScale
* the part is the root part of the vessel
* the vessel is loaded by 'revert to launch' or load/quickload

SQUAD probably knows that there is an API problem because it appeared with the new 'flea' SRB (which had rescaleFactor!=1), and they solved it by avoiding the rescaleFactor.
