### ISSUE TITLE
MK-V ILM - Cannot change storage type except in hangar

### ISSUE THREAD

**Issue by esquila7** [UmbraSpaceIndustries/MKS#617]
Cannot change the storage type of the Mk-V Inflatable Logistics Modules after they have already been built. There's no button on the right click menu to change it in-situ. No problems changing it in the hanger, or when changing the skins on the freight containers.

It makes it more difficult to re-purpose or set up a base in-situ.

**Comment by jd284** [comment]
I suspect this isn't allowed because you'd have to be careful to deflate it before repainting. Otherwise you'd get the deflated capacity, because that's what has to be in the fuelswitch setup for the VAB.

I doubt there's a way to prevent repainting while inflated, or have different capacities for it, so that must be why it's not allowed at all.

That said, if you're careful with this issue, you can add repainting capability with the following ModuleManager config:
```
@PART[MKV_ILM] {
        @MODULE[FStextureSwitch2] {
                @repaintableEVA = true
        }
}
@PART[OKS_Storage_ILM] {
        @MODULE[FStextureSwitch2] {
                @repaintableEVA = true
        }
}
@PART[MKS_Storage_ILM] {
        @MODULE[FStextureSwitch2] {
                @repaintableEVA = true
        }
}
```
