### ISSUE TITLE
UKS Logistics Hub does not function in orbit or on ground

### ISSUE THREAD

**Issue by travin18** [UmbraSpaceIndustries/MKS#843]
Right-clicking on module in orbit or on ground results in to dialog window showing. Cannot enable logistics transfer functions.

**Comment by qwertyza** [comment]
Hi, I confirm this. 
When wheeled off the launchpad, can't transfer anything to orbit = no action when press on kolony logistics

**Comment by h0yer** [comment]
Hi, I'm confirming this issue as well.

Running KSP1.1 1183 x64

Full suite of USI mods, excluding the 'Lite' package and the 'Otter' submersible.
Other running mods:
EVE, Scatterer, SVE, PlanetShine, MJ, KER, IR, RealChute, PersistentRotation, ShipManifest, KW-Rocketry (purely 1.1-pre compatible mod versions, no 1.0.5 variants)

**Comment by taleteller** [comment]
Is this probably related to the following line from latest release description?
```Lgistics Hub and Orbital Logistics have been deprecated for now (no worries, you get a new system soon!)```

**Comment by BobPalmer** [comment]
Yep - it's not working at the moment, it is getting a rework.

**Comment by DanStaal** [comment]
Just a bump - I know the rework is taking longer than planned, can you get this back to working in the meantime?  The part's been re-added, but it no longer works.

**Comment by jazzslider** [comment]
@BobPalmer —[over in the forum](http://forum.kerbalspaceprogram.com/index.php?/topic/72032-11-usi-kolonization-systems-mksoks-0400-planetary-logistics-and-kolony-rewards/&do=findComment&comment=2570494) you indicated that orbital logistics should be working in the latest release.  However, several of us have reported that this isn't the case.

To reproduce:

1. Open up a ship with a logistics hub.
2. Right-click the hub and click the button (I forget at the moment what it's labeled, but there's only one.)
3. In the dialog that opens, click "New Transfer."

Expected behavior: a new dialog opens allowing you to select source, destination, and amount of resources to transfer.

Actual behavior: nothing happens when you click "New Transfer."

**Comment by GrimDarknight** [comment]
So, is anything happening with this? Is it being worked on or ignored in favor of whatever the new system is supposed to be?

**Comment by jazzslider** [comment]
@BobPalmer just curious if there's anything anyone can do to help identify the bug here.  I don't see source code in the repo, just compiled DLLs and CFG files —so it doesn't look like this is something we can create a pull request for.  Still, I know in my case my primary save depends quite heavily on orbital logistics, and I'd love to help resolve this so that my existing bases aren't dead in the water (vacuum?).
