### ISSUE TITLE
suggestion: Add the 'greenhouse' tag to the greenhouse parts

### ISSUE THREAD

**Issue by smjjames** [UmbraSpaceIndustries/MKS#864]
Just a thought I had since I tried to search for 'greenhouse' to narrow things down a bit since I was initially not sure if it was the orbital greenhouse.

**Comment by BobPalmer** [comment]
(Tags in general would be a nice thing)

**Comment by sirreality** [comment]
Tags I could add include MKS, OKS, MK-II, MK-III, Duna, Ranger, Greenhouse.  Which of these would you like me to use?

**Comment by bendavieshe3** [comment]
I was reading up on the tags implementation. It is a bit more complicated than a list of terms: http://forum.kerbalspaceprogram.com/index.php?/topic/137633-syntax-for-11-part-tagging/

- any word in the title is auto-tagged. 
- not just whole words are matched, so you need to worry about collisions (like 'station' and 'ion') and using a useful root (like 'elect' for 'electrical' and 'electricity')
- Each can be made to match from search term to tag, tag to search term or bidirectionally. I only just comprehend what this means.

Based on all of this I don't think USI should overdo tags. Here are some starting points:
* tags that add information and might be somewhat intuitive to use. Like Greenhouse. The problem is that these are hard discover until you find yourself typing them into the search box.
* tags inspired from the hard work that went into tagging stock parts which have functional similarities. E.g. Stock Drills. Station Components. Wheels
* tags for abbreviations commonly used in the UKS documentation and thread but don't appear in the titles

Hopefully this helps!

**Comment by kjnicoletti** [comment]
RoverDude made the intentional decision to remove (most) USI parts from the default KSP categories. Unless this is backed out, tagging USI parts doesn't make them searchable.
