### ISSUE TITLE
OSE.cfg needs updating for new parts

### ISSUE THREAD

**Issue by tarheel1999** [UmbraSpaceIndustries/MKS#939]
The OSE.cfg currently adds OSE modules to the MK3_Fabricator and the MKV_Workshop.  Needs to be changed to the Tundra_AssemblyPlant (?) and the Ranger_Workshop.

**Comment by jd284** [comment]
I tried to change this but it needs more than changing the name of the parts. Getting IndexOutOfRange exceptions.

**Comment by jd284** [comment]
Turns out you also need to add all categories the part should support... and the MaxPartVolume setting no longer exists.
I made a [new version](http://ttdpatch.net/~jdrexler/ksp/misc/MKS_OSE.cfg), seems to work for me at least. Not sure about the efficiency balancing, or whether the Ranger Workshop should omit some categories.
