### ISSUE TITLE
HabRing Other Expandables issues

### ISSUE THREAD

**Issue by TheReadPanda** [UmbraSpaceIndustries/MKS#942]
So I was testing this, and the hab ring weighs 13 tons, the material kits required are 40,000 to expand it.
That weighs roughly 50 tons give or take, plus costs about 100k.

Now here's the issue, I can start with the ring deployed and put it in orbit like that for far less cost and effort than launching it while it is stowed and then sending up the parts.

In addition we have a mysterious loss of mass as the ring gains no weight when expanded but the parts vanish and hence the weight. 

My guess is the ring should take 4,000 not 40,000 to expand. Still something to look at?

**Comment by nevercast** [comment]
I'm wondering about this myself, 40,000 is a huge amount of Material Kits, although other parts do require 8,000 and are smaller.

**Comment by BobPalmer** [comment]
This issue is already fixed in the current update.  Also, yes, those numbers are right.  The ring is very large and is not a balloon - that mass considers all of the structure that would have to be added to the inside to properly kit it out, and it's volume/mass are balanced to its capabilities (i.e. compare the size/mass of that expanded ring to the size of, say, a Mk1-2 pod).
